import {RFValue} from 'react-native-responsive-fontsize';

const Theme = {
  colors: {
    appColor: '#004B9E',
    white: '#ffffff',
    black: '#000000',

    bgColor1: '#004B9E',
    bgColor2: '#ffffff',
    bgColor3: '#000000',

    textColor1: '#004B9E',
    textColor2: '#ffffff',
    textColor3: '#000000',
  },
  icons: {
  },
  fonts: {
    latoBlack: 'Lato-Black',
    latoBlackItalic: 'Lato-BlackItalic',
    latoBold: 'Lato-Bold',
    latoBoldItalic: 'Lato-BoldItalic',
    latoHairline: 'Lato-Hairline',
    latoHairlineItalic: 'Lato-HairlineItalic',
    latoHeavy: 'Lato-Heavy',
    latoHeavyItalic: 'Lato-HeavyItalic',
    latoItalic: 'Lato-Italic',
    latoLight: 'Lato-Light',
    latoLightItalic: 'Lato-LightItalic',
    latoMedium: 'Lato-Medium',
    latoMediumItalic: 'Lato-MediumItalic',
    latoRegular: 'Lato-Regular',
    latoSemibold: 'Lato-Semibold',
    latoSemiboldItalic: 'Lato-SemiboldItalic',
    latoThin: 'Lato-Thin',
    latoThinItalic: 'Lato-ThinItalic',
  },
  responsiveSize: {
    size01: RFValue(1),
    size02: RFValue(2),
    size03: RFValue(3),
    size04: RFValue(4),
    size05: RFValue(5),
    size06: RFValue(6),
    size07: RFValue(7),
    size08: RFValue(8),
    size09: RFValue(9),
    size10: RFValue(10),
    size11: RFValue(11),
    size12: RFValue(12),
    size13: RFValue(13),
    size14: RFValue(14),
    size15: RFValue(15),
    size16: RFValue(16),
    size18: RFValue(18),
    size20: RFValue(20),
    size22: RFValue(22),
    size25: RFValue(25),
    size26: RFValue(26),
    size28: RFValue(28),
    size30: RFValue(30),
    size32: RFValue(32),
    size35: RFValue(35),
    size36: RFValue(36),
    size38: RFValue(38),
    size40: RFValue(40),
    size42: RFValue(42),
    size45: RFValue(45),
    size46: RFValue(46),
    size48: RFValue(48),
    size50: RFValue(50),
    size52: RFValue(52),
    size55: RFValue(55),
    size56: RFValue(56),
    size58: RFValue(58),
    size60: RFValue(60),
    size62: RFValue(62),
    size65: RFValue(65),
    size66: RFValue(66),
    size68: RFValue(68),
    size70: RFValue(70),
    size72: RFValue(72),
    size75: RFValue(75),
    size85: RFValue(85),
    size90: RFValue(90),
    size100: RFValue(100),
    size140: RFValue(140),
    size150: RFValue(150),
  },
};

export default Theme;
